apiVersion: apps/v1
kind: Deployment
metadata:
  name: bucket-apiserver
  namespace: bucket-apiserver
  labels:
    apiserver: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      apiserver: "true"
  template:
    metadata:
      labels:
        apiserver: "true"
    spec:
      serviceAccountName: apiserver
      containers:
      - name: bucket-apiserver
        # build from staging/src/k8s.io/sample-apiserver/artifacts/simple-image/Dockerfile
        # or
        # docker pull registry.k8s.io/e2e-test-images/sample-apiserver:1.17.4
        # docker tag registry.k8s.io/e2e-test-images/sample-apiserver:1.17.4 kube-sample-apiserver:latest
        image: nolancon/bucket-apiserver:v0.0.11
        imagePullPolicy: Always
        args: [ "--etcd-servers=http://localhost:2379" ]
      - name: etcd
        image: registry.k8s.io/etcd:3.7.1-0
